config/routes.rb
SocialThing::Application.routes.draw do

  post 'users/send_password_email', to: 'users#send_password_email', as: 'send_password_email'
  get 'users/reset_password', to: 'users#reset_password', as: 'reset_password'

  get 'session/new', to: 'sessions#new', as: 'login'
  post 'session/create', to: 'sessions#create', as: 'signin'
  delete 'session/destroy', to: 'sessions#destroy', as: 'signout'

  resources :users

  resources :friend_circles
  resources :posts

end

app/models/friend_circle.rb
# == Schema Information
#
# Table name: friend_circles
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  owner_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FriendCircle < ActiveRecord::Base
  attr_accessible :name, :owner_id

  belongs_to :owner, class_name: "User", foreign_key: :owner_id
  has_many :memberships, class_name: "FriendCircleMembership", foreign_key: :friend_circles_id
  has_many :members, through: :memberships, source: :member

  has_many(
    :post_shares,
    class_name: "PostShare",
    foreign_key: :circle_id,
    primary_key: :id
  )

  has_many(
    :posts,
    through: :post_shares,
    source: :post
  )


end

app/controllers/friend_circles_controller.rb
class FriendCirclesController < ApplicationController
  def create
    @user = User.find(params[:user_id])

    ActiveRecord::Base.transaction do
      @circle = FriendCircle.new(name: params[:friend_circle][:name], owner_id: @user.id)
      @circle.save
      @circle.member_ids = params[:friend_circle][:friends]
    end

    redirect_to user_url(@user)
  end

  def edit
    @circle = FriendCircle.find(params[:user_id])
    @user = @circle.owner
  end

  def show
    @circle = FriendCircle.find(params[:user_id])
    @members = @circle.members
  end

  def update

    render :show
  end
end

app/helpers/friend_circles_helper.rb
module FriendCirclesHelper
end

app/views/friend_circles/_friend_circle.html.erb
<p><%= friend_circle.name %>:<br>
  <% i = 1 %>
  <% friend_circle.members.each do |member| %>
    <%= i %>. <%= member.email %><br>
    <% i += 1 %>
  <% end %>
</p>

app/views/friend_circles/edit.html.erb
<h2>Add New Friend Circle</h2>
<form action="friend_circle_url(@circle)" method="post">
  <%= auth %>

  <label>Circle Name: <input type="text" name="friend_circle[name]" value="<%=@circle.name%>"></label>

<input type="hidden" name="_method" value="PUT">

<input type="hidden" name="friend_circle[friends][]" value="">
  <% User.all.each do |user| %>
    <%next if user == current_user %>
    <% html_id = "user_friend_id_#{user.id}" %>
    <%  is_checked =  (@circle.members.includes(user)) ? "checked".html_safe : "" %>
    <p><input type="checkbox"
            name="friend_circle[friends][]"
            value="<%= user.id %>"
            id="<%= html_id %>" <%= 'checked' if @circle.members.include?(user) %>>
    <label for="<%= html_id %>">
      <%= user.email %>
    </label></p>

  <% end %>

  <input type="submit" value="Update Circle">
</form>

app/views/friend_circles/show.html.erb
<h1> <%= "#{@circle.owner.email}'s Circle: #{@circle.name}" %> </h1>

<h3> Members </h3>
  <% @members.each do |member| %>
    <p><%= member.email%></p>

  <% end %>

  <p><%= link_to "Edit #{@circle.name}", edit_user_friend_circle_url(@circle) %></p>