config/routes.rb
SocialThing::Application.routes.draw do

  post 'users/send_password_email', to: 'users#send_password_email', as: 'send_password_email'
  get 'users/reset_password', to: 'users#reset_password', as: 'reset_password'

  get 'session/new', to: 'sessions#new', as: 'login'
  post 'session/create', to: 'sessions#create', as: 'signin'
  delete 'session/destroy', to: 'sessions#destroy', as: 'signout'

  resources :users

  resources :friend_circles
  resources :posts

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  email_token     :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_digest, :session_token
  attr_reader :password

  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  after_initialize :ensure_session_token

  has_many :owned_circles, class_name: "FriendCircle", foreign_key: :owner_id
  has_many :friends, through: :owned_circles, source: :members


  has_many :memberships, class_name: "FriendCircleMembership", foreign_key: :member_id, primary_key: :id

  has_many :circles, through: :memberships, source: :friend_circle

  has_many(
    :authored_posts,
    class_name: "Post",
    foreign_key: :author_id,
    primary_key: :id
  )

  def password=(secret)
      @password = secret
      self.password_digest = BCrypt::Password.create(secret)
    end

    def is_password?(secret)
        BCrypt::Password.new(self.password_digest).is_password?(secret)
    end

    def reset_session_token!
      self.session_token = self.class.generate_session_token
      self.save!
    end


    def self.generate_session_token
      SecureRandom.urlsafe_base64(16)
    end

    def generate_activation_token
      self.activation_token = SecureRandom.urlsafe_base64(16)
    end

    def self.find_by_credentials(email, secret)
      current_user = User.find_by_email(email)

      return nil unless current_user
      current_user.is_password?(secret) ? current_user : nil

    end

    def ensure_session_token
      self.session_token ||= User.generate_session_token
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :ensure_current_user, only: [:show, :edit]

  def new

  end

  def create
    @user = User.new(params[:user])

    if @user.save
      signin(@user)
      redirect_to user_url(@user)
    else
      flash[:notice] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @friend_circles = @user.owned_circles
    @posts = @user.authored_posts
    @post = Post.new
    3.times { @post.links.build }
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to user_url(@user)
    else
      flash[:notice] = @user.errors.full_messages
      render :edit
    end
  end

  def reset_password
    @token = params[:email_token]
    @user = User.find_by_id(params[:id])


    if @token == @user.email_token
      redirect_to edit_user_url(@user)
    else
      flash[:notice] = "AN ERROR OCCURED"
      redirect_to login_url
    end
  end

  def send_password_email
    @user = User.find_by_email(params[:user][:email])
    msg = UserMailer.reset_password_email(@user)
    msg.deliver!
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<form action="<%= user_url(@user) %>" method="POST">
  <% auth %>

  <input type="hidden" name="_method" value="PUT">

  <p><label>Enter Email:
    <input type="text" name="user[email]" value="<%= @user && @user.email %>">
  </label></p>

  <p><label>Enter Password:
    <input type="password" name="user[password]">
  </label></p>

  <input type="submit" value="Update">
</form>

app/views/users/new.html.erb
<h1> Sign Up </h1>
<%= render "sessions/form" %>

app/views/users/show.html.erb
<h1>Profile Page for: <%= current_user.email %></h1>
<p> user_id = <%= current_user.id %> </p>

<h2>Add New Friend Circle</h2>
<form action="<%= user_friend_circles_url(@user) %>" method="post">
  <%= auth %>

  <label>Enter Friend Circle Name: <input type="text" name="friend_circle[name]"></label>

  <% User.all.each do |user| %>
    <%next if user == current_user %>
    <% html_id = "user_friend_id_#{user.id}" %>
    <p><input type="checkbox"
            name="friend_circle[friends][]"
            value="<%= user.id %>"
            id="<%= html_id %>">
    <label for="<%= html_id %>">
      <%= user.email %>
    </label></p>

  <% end %>


  <input type="submit" value="Create Circle">
</form>

<% @friend_circles.each do |circle| %>
  <p><%= link_to circle.name, user_friend_circle_url(circle.id) %></p>

<% end %>
<%= render @friend_circles %>

<h3>Add New Post</h3>
<form action="<%= posts_url %>" method="post">
  <%= auth %>

  <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">

  <label>Body:
    <textarea name="post[body]"></textarea>
  </label>

  <% @post.links.each_with_index do |link, i| %>
    <p><label>
          Link <%= i+1 %><input type="text" name="link[<%=i%>][url]">
       </label>
    </p>
  <% end %>

  <p><label>Which circles would you like to share this post with?
    <% @friend_circles.each_with_index do |circle, i| %>
      <p><label>
            <%= circle.name %><input type="checkbox" name="post_share[<%=i%>][circle_id]" value="<%=circle.id%>">
         </label>
      </p>
    <% end %>
  </label></p>

  <input type="submit" value="Create Post">
</form>

<br>
<h4>POSTS:</h4>

<%= render @user.authored_posts %>